---
apiVersion: v1
kind: Namespace
metadata:
  name: aurora-logs
---
apiVersion: v1
kind: Namespace
metadata:
  name: fluent-bit
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: discovery-sa
  namespace: aurora-logs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: processor-sa
  namespace: aurora-logs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-sa
  namespace: aurora-logs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openobserve-sa
  namespace: aurora-logs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: fluent-bit
