---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
  namespace: aurora-logs
  labels:
    app: processor
    component: log-processor
spec:
  replicas: 1  # Start with 1, HPA will scale as needed
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
        component: log-processor
    spec:
      serviceAccountName: processor-sa
      nodeSelector:
        kubernetes.io/hostname: ip-172-16-30-241.ec2.internal  # aurora-node-2
      dnsPolicy: ClusterFirst
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: processor
        image: 072006186126.dkr.ecr.us-east-1.amazonaws.com/aurora-log-system:processor-latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: OPENOBSERVE_USER
          valueFrom:
            secretKeyRef:
              name: openobserve-credentials
              key: admin-email
        - name: OPENOBSERVE_PASS
          valueFrom:
            secretKeyRef:
              name: openobserve-credentials
              key: admin-password
        ports:
        - name: metrics
          containerPort: 9090
          protocol: TCP
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        volumeMounts:
        - name: tmp
          mountPath: /tmp
          readOnly: false
        - name: cache
          mountPath: /cache
          readOnly: false
      volumes:
      - name: tmp
        emptyDir:
          sizeLimit: 1Gi
      - name: cache
        emptyDir:
          sizeLimit: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: processor-service
  namespace: aurora-logs
  labels:
    app: processor
    component: log-processor
spec:
  selector:
    app: processor
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
  type: ClusterIP