apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: aurora-logs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      serviceAccountName: kafka-sa
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.5.0.arm64  # Official Confluent Kafka ARM64 image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
          name: broker
        - containerPort: 9093
          name: controller
        env:
        # KRaft mode configuration
        - name: CLUSTER_ID
          value: "MkU3OEVBNzE2Q0IyNDczNg"
        - name: KAFKA_NODE_ID
          value: "1"
        - name: KAFKA_PROCESS_ROLES
          value: "broker,controller"
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: "1@localhost:9093"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-service.aurora-logs.svc.cluster.local:9092"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "PLAINTEXT"
        - name: KAFKA_LOG_DIRS
          value: "/var/lib/kafka/data"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: "0"
        - name: KAFKA_LOG_RETENTION_HOURS
          value: "168"
        - name: KAFKA_LOG_SEGMENT_BYTES
          value: "1073741824"
        # JVM Settings
        - name: KAFKA_HEAP_OPTS
          value: "-Xmx1G -Xms1G"
        - name: KAFKA_JVM_PERFORMANCE_OPTS
          value: "-XX:+UseG1GC -XX:MaxGCPauseMillis=20"
        resources:
          requests:
            cpu: "250m"
            memory: "1Gi"
          limits:
            cpu: "500m"
            memory: "2Gi"
        volumeMounts:
        - name: kafka-data
          mountPath: /var/lib/kafka
        - name: kafka-config
          mountPath: /etc/kafka
        command:
        - bash
        - -c
        - |
          # Format log directories for KRaft mode
          kafka-storage format -t ${CLUSTER_ID} -c /etc/kafka/server.properties --ignore-formatted
          
          # Start Kafka
          kafka-server-start /etc/kafka/server.properties
      volumes:
      - name: kafka-data
        persistentVolumeClaim:
          claimName: kafka-data-pvc
      - name: kafka-config
        configMap:
          name: kafka-server-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-server-config
  namespace: aurora-logs
data:
  server.properties: |
    # KRaft Configuration
    node.id=1
    process.roles=broker,controller
    controller.quorum.voters=1@localhost:9093
    
    # Listeners
    listeners=PLAINTEXT://:9092,CONTROLLER://:9093
    advertised.listeners=PLAINTEXT://kafka-service.aurora-logs.svc.cluster.local:9092
    listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    controller.listener.names=CONTROLLER
    inter.broker.listener.name=PLAINTEXT
    
    # Log Configuration
    log.dirs=/var/lib/kafka/data
    num.partitions=10
    default.replication.factor=1
    min.insync.replicas=1
    
    # Log Retention
    log.retention.hours=168
    log.segment.bytes=1073741824
    log.retention.check.interval.ms=300000
    
    # Other Settings
    auto.create.topics.enable=true
    delete.topic.enable=true
    compression.type=producer
    
    # Internal Topic Settings  
    offsets.topic.replication.factor=1
    transaction.state.log.replication.factor=1
    transaction.state.log.min.isr=1
    
    # Performance
    num.network.threads=8
    num.io.threads=8
    socket.send.buffer.bytes=102400
    socket.receive.buffer.bytes=102400
    socket.request.max.bytes=104857600
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: aurora-logs
spec:
  ports:
  - name: broker
    port: 9092
    targetPort: 9092
  - name: controller
    port: 9093
    targetPort: 9093
  selector:
    app: kafka
  type: ClusterIP