apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: discovery-pdb
  namespace: aurora-logs
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: discovery
  unhealthyPodEvictionPolicy: AlwaysAllow
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: processor-pdb
  namespace: aurora-logs
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: processor
  unhealthyPodEvictionPolicy: AlwaysAllow
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kafka-pdb
  namespace: aurora-logs
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: kafka
  unhealthyPodEvictionPolicy: AlwaysAllow
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: openobserve-pdb
  namespace: aurora-logs
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: openobserve
  unhealthyPodEvictionPolicy: AlwaysAllow