apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: aurora-logs
  labels:
    app: kafka
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for StatefulSet
  ports:
  - name: broker
    port: 9092
    targetPort: 9092
    protocol: TCP
  - name: controller
    port: 9093
    targetPort: 9093
    protocol: TCP
  selector:
    app: kafka
