apiVersion: v1
kind: Service
metadata:
  name: openobserve-service
  namespace: aurora-logs
  labels:
    app: openobserve
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5080
    targetPort: 5080
    protocol: TCP
  selector:
    app: openobserve
