apiVersion: v1
kind: Service
metadata:
  name: processor-service
  namespace: aurora-logs
  labels:
    app: processor
    component: backend
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: processor
---
apiVersion: v1
kind: Service
metadata:
  name: processor-headless
  namespace: aurora-logs
  labels:
    app: processor
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for service discovery
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
  selector:
    app: processor