apiVersion: v1
kind: Service
metadata:
  name: valkey-service
  namespace: aurora-logs
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  selector:
    app: valkey
---
apiVersion: v1
kind: Service
metadata:
  name: valkey-headless
  namespace: aurora-logs
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  selector:
    app: valkey