---
# Namespace and Service Accounts
apiVersion: v1
kind: Namespace
metadata:
  name: aurora-logs
  labels:
    name: aurora-logs
    monitoring: enabled
---
# Service Account for Discovery
apiVersion: v1
kind: ServiceAccount
metadata:
  name: discovery-sa
  namespace: aurora-logs
  labels:
    app: discovery
    # EKS Pod Identity will be configured separately via AWS API
---
# Service Account for Processor
apiVersion: v1
kind: ServiceAccount
metadata:
  name: processor-sa
  namespace: aurora-logs
  labels:
    app: processor
    # EKS Pod Identity will be configured separately via AWS API
---
# Service Account for OpenObserve
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openobserve-sa
  namespace: aurora-logs
  labels:
    app: openobserve
    # EKS Pod Identity will be configured separately via AWS API
---
# Service Account for OTEL Collector
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector-sa
  namespace: aurora-logs
---
# Service Account for Fluent Bit
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit-sa
  namespace: aurora-logs
---
# RBAC for OTEL Collector
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - deployments
  - replicasets
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-collector
subjects:
- kind: ServiceAccount
  name: otel-collector-sa
  namespace: aurora-logs
---
# RBAC for Fluent Bit
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  - nodes
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit
subjects:
- kind: ServiceAccount
  name: fluent-bit-sa
  namespace: aurora-logs