---
apiVersion: v1
kind: Service
metadata:
  name: valkey-service
  namespace: aurora-logs
spec:
  selector:
    app: valkey
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
  namespace: aurora-logs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-172-16-30-241.ec2.internal  # aurora-node-2
      containers:
      - name: valkey
        image: valkey/valkey:8.1.3
        ports:
        - containerPort: 6379
          name: redis
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        env:
        - name: VALKEY_PASSWORD
          value: ""  # No password for internal use
        command: ["valkey-server"]
        args: 
        - "--bind"
        - "0.0.0.0"
        - "--protected-mode"
        - "no"
        - "--maxmemory"
        - "768mb"
        - "--maxmemory-policy"
        - "allkeys-lru"
        - "--save"
        - ""  # Disable persistence for cache-only use
        - "--appendonly"
        - "no"
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "valkey-cli ping | grep PONG"
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: valkey-data
          mountPath: /data
      volumes:
      - name: valkey-data
        emptyDir:
          sizeLimit: 2Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: valkey-config
  namespace: aurora-logs
data:
  valkey.conf: |
    # Basic configuration
    bind 0.0.0.0
    protected-mode no
    port 6379
    
    # Memory management
    maxmemory 768mb
    maxmemory-policy allkeys-lru
    
    # Disable persistence (cache only)
    save ""
    appendonly no
    
    # Performance tuning
    tcp-backlog 511
    timeout 0
    tcp-keepalive 300
    
    # Slow log
    slowlog-log-slower-than 10000
    slowlog-max-len 128
    
    # Client output buffer limits
    client-output-buffer-limit normal 0 0 0
    client-output-buffer-limit replica 256mb 64mb 60
    client-output-buffer-limit pubsub 32mb 8mb 60