---
# Optimized single-node Kafka with auto-create topics enabled
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: aurora-logs
  labels:
    app: kafka
    component: message-broker
spec:
  replicas: 1  # Single node for cost savings
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
        tier: messaging
    spec:
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      # Deploy only on aurora-node-2
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: eks.amazonaws.com/nodegroup
                operator: In
                values:
                - aurora-node-2
      containers:
      - name: kafka
        image: bitnami/kafka:4.0.0
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "200m"     # Minimal CPU
            memory: "1Gi"   # Minimal memory
          limits:
            cpu: "500m"
            memory: "2Gi"
        env:
        # Bitnami Kafka KRaft configuration
        - name: BITNAMI_DEBUG
          value: "true"
        - name: KAFKA_ENABLE_KRAFT
          value: "yes"
        - name: KAFKA_CFG_NODE_ID
          value: "1"
        - name: KAFKA_CFG_PROCESS_ROLES
          value: "controller,broker"
        - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
          value: "PLAINTEXT"
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
        - name: KAFKA_CFG_LISTENERS
          value: "PLAINTEXT://:9092,CONTROLLER://:9093"
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-service.aurora-logs.svc.cluster.local:9092"
        - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
          value: "1@localhost:9093"
        - name: KAFKA_KRAFT_CLUSTER_ID
          value: "MkU3OEVBNzE0QTI2Qjk2NA"
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        
        # Enable auto-create topics
        - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_CFG_NUM_PARTITIONS
          value: "10"  # Default partitions for auto-created topics
        
        # Performance optimizations for single node
        - name: KAFKA_CFG_DEFAULT_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_CFG_MIN_INSYNC_REPLICAS
          value: "1"
        - name: KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"
        
        # Memory optimizations
        - name: KAFKA_HEAP_OPTS
          value: "-Xmx768M -Xms512M"  # Reduced heap
        - name: KAFKA_JVM_PERFORMANCE_OPTS
          value: "-XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:+UseCompressedOops -XX:+UseStringDeduplication"
        
        # Log retention (1 day for cost savings)
        - name: KAFKA_CFG_LOG_RETENTION_HOURS
          value: "24"
        - name: KAFKA_CFG_LOG_RETENTION_BYTES
          value: "1073741824"  # 1GB per partition
        - name: KAFKA_CFG_LOG_SEGMENT_BYTES
          value: "134217728"   # 128MB segments
        
        # Compression
        - name: KAFKA_CFG_COMPRESSION_TYPE
          value: "lz4"
        - name: KAFKA_CFG_LOG_CLEANUP_POLICY
          value: "delete"
        
        # Network optimizations
        - name: KAFKA_CFG_NUM_NETWORK_THREADS
          value: "2"  # Reduced threads
        - name: KAFKA_CFG_NUM_IO_THREADS
          value: "2"
        - name: KAFKA_CFG_SOCKET_SEND_BUFFER_BYTES
          value: "102400"
        - name: KAFKA_CFG_SOCKET_RECEIVE_BUFFER_BYTES
          value: "102400"
        - name: KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES
          value: "104857600"
        
        ports:
        - name: kafka
          containerPort: 9092
          protocol: TCP
        - name: controller
          containerPort: 9093
          protocol: TCP
        volumeMounts:
        - name: kafka-data
          mountPath: /bitnami/kafka
          subPath: kafka
        livenessProbe:
          tcpSocket:
            port: kafka
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: kafka
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: kafka-data
        persistentVolumeClaim:
          claimName: kafka-data-pvc
---
# Service for Kafka
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: aurora-logs
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    targetPort: 9092
    name: kafka
  - port: 9093
    targetPort: 9093
    name: controller
  selector:
    app: kafka
  type: ClusterIP