---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openobserve
  namespace: aurora-logs
  labels:
    app: openobserve
    component: log-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openobserve
  template:
    metadata:
      labels:
        app: openobserve
        component: log-analytics
    spec:
      serviceAccountName: openobserve-sa
      nodeSelector:
        kubernetes.io/hostname: ip-172-16-30-241.ec2.internal  # aurora-node-2
      containers:
      - name: openobserve
        image: openobserve/openobserve:v0.15.0-rc4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5080
          name: http
        env:
        # OpenObserve Configuration
        - name: ZO_DATA_DIR
          value: "/data"
        - name: ZO_HTTP_PORT
          value: "5080"
        - name: ZO_ROOT_USER_EMAIL
          value: "admin@example.com"
        - name: ZO_ROOT_USER_PASSWORD
          value: "Complexpass#123"
        - name: ZO_S3_BUCKET_NAME
          value: "company-aurora-logs-poc"
        - name: ZO_S3_REGION_NAME
          value: "us-east-1"
        - name: ZO_S3_SERVER_URL
          value: "https://s3.us-east-1.amazonaws.com"
        - name: ZO_STORAGE_TYPE
          value: "s3"
        - name: AWS_REGION
          value: "us-east-1"
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
        # Performance settings
        - name: ZO_MEMORY_CACHE_ENABLED
          value: "true"
        - name: ZO_MEMORY_CACHE_CACHE_LATEST_FILES
          value: "true"
        - name: ZO_MEMORY_CACHE_MAX_SIZE
          value: "2048"
        - name: ZO_PAYLOAD_LIMIT
          value: "209715200"
        - name: ZO_MAX_FILE_SIZE_ON_DISK
          value: "128"
        - name: ZO_FILE_PUSH_INTERVAL
          value: "60"
        - name: ZO_COMPACT_ENABLED
          value: "true"
        - name: ZO_COMPACT_INTERVAL
          value: "3600"
        # Auth settings
        - name: ZO_AUTH_COOKIE_SECURE
          value: "false"
        - name: ZO_COOKIE_SAME_SITE_LAX
          value: "true"
        # Features
        - name: ZO_UI_ENABLED
          value: "true"
        - name: ZO_METRICS_DEDUP_ENABLED
          value: "true"
        - name: ZO_PROMETHEUS_ENABLED
          value: "true"
        resources:
          requests:
            cpu: "500m"
            memory: "2Gi"
          limits:
            cpu: "1000m"
            memory: "4Gi"
        volumeMounts:
        - name: data
          mountPath: /data
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5080
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: openobserve-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: openobserve-service
  namespace: aurora-logs
  labels:
    app: openobserve
    component: log-analytics
spec:
  ports:
  - name: http
    port: 5080
    targetPort: 5080
  selector:
    app: openobserve
  type: ClusterIP