---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
  namespace: aurora-logs
  labels:
    app: processor
    component: log-processor
spec:
  replicas: 1  # Start with 1, HPA will scale as needed
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
        component: log-processor
    spec:
      serviceAccountName: processor-sa
      dnsPolicy: ClusterFirst
      # Deploy only on aurora-node-2
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: eks.amazonaws.com/nodegroup
                operator: In
                values:
                - aurora-node-2
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - processor
              topologyKey: kubernetes.io/hostname
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: processor
        image: 072006186126.dkr.ecr.us-east-1.amazonaws.com/aurora-log-system:processor-latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        # Fluent Bit TCP forward configuration
        - name: LOG_FORWARD_ENABLED
          value: "true"
        - name: LOG_FORWARD_HOST
          value: "localhost"  # Sidecar container
        - name: LOG_FORWARD_PORT
          value: "24224"
        - name: PARSING_MODE
          value: "passthrough"  # Let Fluent Bit do parsing
        ports:
        - name: metrics
          containerPort: 9090
          protocol: TCP
        - name: health
          containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
        startupProbe:
          httpGet:
            path: /healthz
            port: health
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: health
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      # Fluent Bit sidecar for log parsing
      - name: fluent-bit
        image: fluent/fluent-bit:4.0.5-arm64
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        ports:
        - name: forward
          containerPort: 24224
          protocol: TCP
        volumeMounts:
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
        - name: fluent-bit-parsers
          mountPath: /fluent-bit/etc/parsers.conf
          subPath: parsers.conf
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
      - name: fluent-bit-parsers
        configMap:
          name: fluent-bit-parsers
---
# Service for processor metrics
apiVersion: v1
kind: Service
metadata:
  name: processor-metrics
  namespace: aurora-logs
  labels:
    app: processor
    component: metrics
spec:
  type: ClusterIP
  selector:
    app: processor
  ports:
  - name: metrics
    port: 9090
    targetPort: metrics
    protocol: TCP