---
# HPA for Processor - Scales based on CPU/Memory and Kafka lag
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: processor-hpa
  namespace: aurora-logs
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: processor
  minReplicas: 1   # Always keep at least 1 running
  maxReplicas: 10  # Maximum replicas
  metrics:
  # Scale based on CPU
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60  # Scale up at 60% CPU
  # Scale based on memory
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70  # Scale up at 70% memory
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # Wait 5 minutes before scaling down
      policies:
      - type: Percent
        value: 50    # Remove max 50% of pods at once
        periodSeconds: 60
      - type: Pods
        value: 1     # Remove max 1 pod at a time
        periodSeconds: 60
      selectPolicy: Min  # Use the most conservative policy
    scaleUp:
      stabilizationWindowSeconds: 30   # Quick scale up (30 seconds)
      policies:
      - type: Percent
        value: 100   # Double the pods
        periodSeconds: 30
      - type: Pods
        value: 2     # Add max 2 pods at a time
        periodSeconds: 30
      selectPolicy: Max  # Use the most aggressive policy
---
# HPA for Discovery - Conservative scaling
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: discovery-hpa
  namespace: aurora-logs
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: discovery
  minReplicas: 1
  maxReplicas: 2  # Discovery doesn't need many replicas
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80  # Higher threshold since discovery is lightweight
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600  # Wait 10 minutes before scaling down
      policies:
      - type: Pods
        value: 1
        periodSeconds: 300  # Remove 1 pod every 5 minutes
    scaleUp:
      stabilizationWindowSeconds: 60   # Wait 1 minute before scaling up
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60   # Add 1 pod every minute